compile: assignment1.c assignment2.c assignment3.c assignment4.c helloworld.c
	gcc -o assignment1 assignment1.c
	gcc -o assignment2 assignment2.c
	gcc -o assignment3 assignment3.c
	gcc -o assignment4 assignment4.c
	gcc -o helloworld helloworld.c
runAssignment1:
	./assignment1
runAssignment2:
	./assignment2
runAssignment3:
	./assignment3
runAssignment4:
	./assignment4
clean:
	rm assignment1
	rm assignment2
	rm assignment3
	rm assignment4
	rm helloworld
